CREATE TABLE ZLECENIA(		
ID SERIAL PRIMARY KEY,
DATA_ROZPOCZECIA DATE DEFAULT CURRENT_DATE,
NAZWA VARCHAR(20),
ZESPOL INT REFERENCES DZIALY (ID_DZIALU),		
TERMIN DATE NOT NULL CHECK (TERMIN > DATA_ROZPOCZECIA), 
UKONCZONE BOOL NOT NULL,
KOSZT DECIMAL CHECK (KOSZT >= 0));

SELECT * FROM ZLECENIA;

CREATE TABLE WLASCICIELE(
ID SERIAL,
NAZWA VARCHAR(30) NOT NULL,
TELEFON INT,
UWAGI VARCHAR(30),
CONSTRAINT PK_WLASCICIELE PRIMARY KEY (ID));

select * from wlasciciele;

CREATE TABLE POJAZDY(
ID SERIAL PRIMARY KEY, 
NRVIN INT UNIQUE, 
MARKA VARCHAR(30) NOT NULL, 
KOLOR VARCHAR(30) NOT NULL, 
WLASCICIEL INT,
UWAGI VARCHAR(30),
CONSTRAINT FK_WLASCICIELE FOREIGN KEY (WLASCICIEL) REFERENCES WLASCICIELE (ID));

select * from pojazdy;

CREATE TABLE NAPRAWY(
ID SERIAL PRIMARY KEY, 
POJAZD INT REFERENCES POJAZDY (ID),
DATA_ROZP DATE DEFAULT CURRENT_DATE NOT NULL, 
DATA_NAPRAWY DATE CHECK (DATA_NAPRAWY < DATA_ROZP), 
KOSZT DECIMAL CHECK (KOSZT >= 0), 
OPIS_ZGLOSZENIA VARCHAR(100) NOT NULL);

select * from naprawy;

CREATE TABLE CZESCI(
ID SERIAL, 
NAZWA VARCHAR(30),
CENA DECIMAL, 
PRODUCENT VARCHAR(30), 
DOSTAWCA VARCHAR(30),
CONSTRAINT PK_CZESCI PRIMARY KEY (ID),
CONSTRAINT NAZWA_CHECK CHECK (NAZWA NOT LIKE ''),
CONSTRAINT CENA_CHECK CHECK (CENA >= 0))

select * from czesci;

CREATE TABLE UZYTECZESCI(
ID_CZ INT REFERENCES CZESCI (ID), 
ID_NAPRAWY INT REFERENCES NAPRAWY (ID), 
ILOSC INT NOT NULL CHECK (ILOSC >= 0),
UWAGI VARCHAR(30),
CONSTRAINT PK_ID_CZ_ID_NAPRAWY PRIMARY KEY (ID_CZ, ID_NAPRAWY))

select * from uzyteczesci;

